yrdy

diff --git a/.github/workflows/deploy_to_ghcr_custom_tag.yaml b/.github/workflows/deploy_to_ghcr_custom_tag.yaml
--- a/.github/workflows/deploy_to_ghcr_custom_tag.yaml
+++ b/.github/workflows/deploy_to_ghcr_custom_tag.yaml
@@ -23,6 +23,30 @@ jobs:
       - name: Checkout specific tag
         run: git checkout tags/v${{ github.event.inputs.tag }}
 
+      - name: Run Snyk to check for code vulnerabilities
+        uses: snyk/actions/node@master
+        with:
+          command: code test
+          args: --sarif-file-output=snyk-code.sarif --severity-threshold=high
+
+      # - name: Check SARIF for critical vulnerabilities
+      #   run: |
+      #     # Parse the SARIF report to check for critical vulnerabilities
+      #     CRITICAL_COUNT=$(jq '[.runs[].results[] | select(.level == "error")] | length' snyk-report.sarif)
+      #     echo "Number of critical vulnerabilities found: $CRITICAL_COUNT"
+      #     if [ "$CRITICAL_COUNT" -gt 0 ]; then
+      #       echo "Critical vulnerabilities found! Failing pipeline."
+      #       exit 1
+      #     fi
+      #   shell: bash
+
+      - name: Run Snyk to check for dependency vulnerabilities
+        uses: snyk/actions/node@master
+        with:
+          args: --sarif-file-output=snyk-code.sarif --severity-threshold=critical
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v3
         with:
@@ -39,3 +63,14 @@ jobs:
           docker push ghcr.io/$GITHUB_REPO:$TAG
         env:
           GITHUB_REPO: ${{ github.repository }}
+  
+      - name: Run Snyk to check for container vulnerabilities
+        uses: snyk/actions/node@master
+        with:
+          command: code test ghcr.io/$GITHUB_REPO:$TAG
+          args: --sarif-file-output=snyk-container.sarif --file=Dockerfile --severity-threshold=critical
+
+      - name: Upload sarif files
+        uses: github/codeql-action/upload-sarif@v3
+        with:
+          sarif_file: "**/*.sarif"
