try using script for critical vulnerabilities

diff --git a/.github/workflows/deploy_to_ghcr_custom_tag.yaml b/.github/workflows/deploy_to_ghcr_custom_tag.yaml
--- a/.github/workflows/deploy_to_ghcr_custom_tag.yaml
+++ b/.github/workflows/deploy_to_ghcr_custom_tag.yaml
@@ -32,25 +32,25 @@ jobs:
       # - name: Run Snyk to check for code vulnerabilities
       #   id: snyk_code 
       #   uses: snyk/actions/node@master
+      #   continue-on-error: true
       #   with:
       #     command: code test
-      #     args: --sarif-file-output=snyk/code.sarif --severity-threshold=high
+      #     args: --sarif-file-output=snyk/code.sarif --report
 
       # - name: Check SARIF for critical vulnerabilities
       #   run: |
-      #     # Parse the SARIF report to check for critical vulnerabilities
-      #     CRITICAL_COUNT=$(jq '[.runs[].results[] | select(.level == "error")] | length' snyk-report.sarif)
+      #     CRITICAL_COUNT=$(jq '[.runs[].results[] | select(.level == "error")] | length' snyk/code.sarif)
       #     echo "Number of critical vulnerabilities found: $CRITICAL_COUNT"
       #     if [ "$CRITICAL_COUNT" -gt 0 ]; then
       #       echo "Critical vulnerabilities found! Failing pipeline."
       #       exit 1
       #     fi
-      #   shell: bash
 
       - name: Run Snyk to check for dependency vulnerabilities
         uses: snyk/actions/node@master
         with:
           command: monitor
+          args: --all-projects
 
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v3
@@ -77,7 +77,16 @@ jobs:
         uses: snyk/actions/node@master
         with:
           command: container test ghcr.io/${{ env.GITHUB_REPO }}:${{ env.TAG }}
-          args: --sarif-file-output=snyk/container.sarif --file=Dockerfile --severity-threshold=critical
+          args: --sarif-file-output=snyk/container.sarif --file=Dockerfile --report
+
+      - name: Check SARIF for critical vulnerabilities
+        run: |
+          CRITICAL_COUNT=$(jq '[.runs[].results[] | select(.level == "error")] | length' snyk/container.sarif)
+          echo "Number of critical vulnerabilities found: $CRITICAL_COUNT"
+          if [ "$CRITICAL_COUNT" -gt 0 ]; then
+            echo "Critical vulnerabilities found! Failing pipeline."
+            exit 1
+          fi
 
       - name: Upload sarif files
         uses: github/codeql-action/upload-sarif@v3
